In [1]:
import numpy as np

In [2]:
# Vectors
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

In [4]:
# Matrices
A = np.array([[2, 1, 3],
              [1, 0, 2],
              [4, 1, 1]])

In [5]:
B = np.array([[1, 2, 0],
              [3, 1, 4],
              [2, 5, 1]])

In [7]:
# Vector addition
print("Addition:")
print(a + b)

Addition:
[ 3  7 11]


In [8]:
# Vector subtraction
print("Subtraction:")
print(a - b)

Subtraction:
[1 1 1]


In [9]:
# Dot product
print("Dot Product:")
print(np.dot(a, b))

Dot Product:
44


In [10]:
# Matrix addition
print("Matrix Addition:")
print(A + B)

Matrix Addition:
[[3 3 3]
 [4 1 6]
 [6 6 2]]


In [11]:
# Matrix multiplication
print("Matrix Multiplication:")
print(np.dot(A, B))

Matrix Multiplication:
[[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]


In [12]:
# Determinant
d = np.linalg.det(A)
print("Determinant:")
print(d)

Determinant:
6.0


In [13]:
# Inverse
if d != 0:
    print("Inverse:")
    print(np.linalg.inv(A))

Inverse:
[[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]


In [ ]:
# Eigenvalues and Eigenvectors
value, vector = np.linalg.eig(A)

print("Eigenvalues:")
print(value)

print("Eigenvectors:")
print(vector)

Eigenvalues:
[ 5.54138127 -2.         -0.54138127]
Eigenvectors:
[[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


In [ ]:
'''#-------------------------------------------
a + b → adds two vectors.
a - b → subtracts two vectors.
np.dot(a, b) → finds dot product.
A + B → adds two matrices.
np.dot(A, B) → multiplies two matrices.
np.linalg.det(A) → finds determinant.
np.linalg.inv(A) → finds inverse.
np.linalg.eig(A) → finds eigenvalues and eigenvectors.
------------------------------------------------------'''

In [15]:
import numpy as np

In [18]:
# Data
sales_success = [0.65, 0.35]

customer_segments = ["Premium", "Regular"]

segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}

# Probability of successful sales
print("Probability of Successful Sales:")
print(sales_success[0])

# Probability of unsuccessful sales
print("Probability of Unsuccessful Sales:")
print(sales_success[1])

# Conditional Probability
print("\nPurchase Probability by Customer Segment")
for segment in customer_segments:
    print(segment, ":", segment_purchase_probability[segment])

Probability of Successful Sales:
0.65
Probability of Unsuccessful Sales:
0.35

Purchase Probability by Customer Segment
Premium : 0.8
Regular : 0.5


In [19]:
#task-2
import numpy as np
from scipy.stats import binom

In [ ]:
# -------------------------
# 1. Probability of Sales
# -------------------------

sales_success = [0.65, 0.35]

print("Successful Sales Probability:", sales_success[0])
print("Unsuccessful Sales Probability:", sales_success[1])

Successful Sales Probability: 0.65
Unsuccessful Sales Probability: 0.35


In [21]:
# -------------------------
# 2. Conditional Probability
# -------------------------

segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}

print("\nConditional Probability")

print("Premium Customer Purchase Probability:",
      segment_purchase_probability["Premium"])

print("Regular Customer Purchase Probability:",
      segment_purchase_probability["Regular"])


Conditional Probability
Premium Customer Purchase Probability: 0.8
Regular Customer Purchase Probability: 0.5


In [22]:
# -------------------------
# 3. Bayes Theorem
# -------------------------

P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80

P_A_given_B = (P_B_given_A * P_A) / P_B

print("\nBayes Theorem Result")
print("P(A|B) =", P_A_given_B)


Bayes Theorem Result
P(A|B) = 0.5161290322580646


In [23]:
# -------------------------
# 4. Binomial Distribution
# -------------------------

n_trials = 20
success_prob = 0.65

binomial_result = binom.pmf(13, n_trials, success_prob)

print("\nBinomial Distribution")
print("Probability of exactly 13 successes:", binomial_result)




Binomial Distribution
Probability of exactly 13 successes: 0.18440118638393133


In [ ]:
# -------------------------
# 5. Normal Distribution
# -------------------------

normal_mean = 50
normal_std = 10

normal_data = np.random.normal(normal_mean,normal_std,10)

print("\nNormal Distribution Sample")
print(normal_data)



Normal Distribution Sample
[47.90924435 41.66214044 41.16627884 53.83689009 63.93758089 45.15751147
 59.37769924 49.82307442 61.07210608 66.10720667]


In [ ]:
# -------------------------
# 6. Uniform Distribution
# -------------------------

uniform_low = 0
uniform_high = 1

uniform_data = np.random.uniform(uniform_low, uniform_high,10)

print("\nUniform Distribution Sample")
print(uniform_data)



Uniform Distribution Sample
[0.54940059 0.40344125 0.74724628 0.26166527 0.41508882 0.01602052
 0.60419146 0.65356941 0.31823575 0.93334981]


In [26]:
#Task-3

import numpy as np
from statistics import mode
from scipy.stats import skew, kurtosis


In [27]:
# Dataset
sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
              190, 200, 210, 195, 185, 175, 165, 155, 145, 135]


In [28]:
# Mean
print("Mean:", np.mean(sales_data))

# Median
print("Median:", np.median(sales_data))

# Mode
print("Mode:", mode(sales_data))

# Range
print("Range:", max(sales_data) - min(sales_data))

# Variance
print("Variance:", np.var(sales_data))

# Standard Deviation
print("Standard Deviation:", np.std(sales_data))

# Skewness
s = skew(sales_data)
print("Skewness:", s)

# Kurtosis
k = kurtosis(sales_data)
print("Kurtosis:", k)

# Interpretation
if s > 0:
    print("Dataset is Positively Skewed")
elif s < 0:
    print("Dataset is Negatively Skewed")
else:
    print("Dataset is Symmetric")



Mean: 165.5
Median: 165.0
Mode: 135
Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356
Skewness: 0.030143346252736614
Kurtosis: -0.7069943289224954
Dataset is Positively Skewed


In [ ]:
"""
Interpretation
If Skewness = 0, the data is symmetric.
If Skewness > 0, the data is positively skewed (tail on the right).
If Skewness < 0, the data is negatively skewed (tail on the left).

For this dataset, the skewness is very close to 0, so the dataset is approximately symmetric."""