In [1]:
import numpy as np

In [6]:
#1.Create a 1D Numpy Array

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("week1 Temperatures:")
print(temperatures_w1)


week1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [8]:
#2 Inspecting and properties
print("\nShape of the array:")
print(temperatures_w1.shape)

print("\nData Type:")
print(temperatures_w1.dtype)

print("\nNumber of elements:")
print(temperatures_w1.size)



Shape of the array:
(7,)

Data Type:
float64

Number of elements:
7


In [9]:
#Array Operations
#celsius to fahrenheit
fahrenheit = (temperatures_w1 * 9/5) + 32
print("\nTemperatures in Fahrenheit:")
print(fahrenheit)

print("\nMaximum Temperature:")
print(np.max(temperatures_w1))

print("\nMinimum Temperature:")
print(np.min(temperatures_w1))

print("mean Temperature:")
print(np.mean(temperatures_w1))



Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature:
26.1

Minimum Temperature:
20.8
mean Temperature:
23.542857142857144


In [11]:
#4.Array slicing and indexing
print("\nFirst three temperatures:")
print(temperatures_w1[:3])

print("\nweekend temperatures:")
print(temperatures_w1[5:])

print("\nmiddle three days temperatures:")
print(temperatures_w1[2:5])


First three temperatures:
[22.5 25.3 20.8]

weekend temperatures:
[24.8 21.9]

middle three days temperatures:
[20.8 23.4 26.1]


In [12]:
#create a 2D Array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [21.0, 24.5, 19.8, 22.0, 25.0, 23.5, 20.5],  # Week 2
    [23.0, 26.0, 21.5, 24.0, 27.0, 25.5, 22.0]   # Week 3
])

print ("\n2D Array of Temperatures:")
print(temperatures)


2D Array of Temperatures:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [21.  24.5 19.8 22.  25.  23.5 20.5]
 [23.  26.  21.5 24.  27.  25.5 22. ]]


In [14]:
# 6. Inspect and Slice the 2D Array
print("\nShape of the 2D array:")
print(temperatures.shape)
print("\ndata type of the 2D array:")
print(temperatures.dtype)
print ("total number of elements in the 2D array:")
print(temperatures.size)
print("\nTemperatures for Week 1:")
print(temperatures[0])
print("\nTemperatures for Week 2:")
print(temperatures[1])
print("\nweekend temperatures for all  weeks:")
print(temperatures[:, -2:])





Shape of the 2D array:
(3, 7)

data type of the 2D array:
float64
total number of elements in the 2D array:
21

Temperatures for Week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Temperatures for Week 2:
[21.  24.5 19.8 22.  25.  23.5 20.5]

weekend temperatures for all  weeks:
[[24.8 21.9]
 [23.5 20.5]
 [25.5 22. ]]


In [21]:
import pandas as pd


In [22]:
# Create marks series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)

# Print series
print("Student Marks")
print(marks)


Student Marks
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [26]:
#2.Indexing and slicing
print("\n1st Rank Mark")
print(marks["Rank1"])
print("\nTop 3 Ranks")
print(marks.loc[["Rank1", "Rank2", "Rank3"]])

print("\n3rd Rank Mark")
print(marks.iloc[2])

print("\nMarks Greater Than 90")
print(marks[marks > 90])



1st Rank Mark
95

Top 3 Ranks
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank Mark
89

Marks Greater Than 90
Rank1    95
Rank2    92
dtype: int64


In [27]:
# 3. Manipulating Series

marks["Rank1"] = 100
print("\nAfter Changing Rank1 Mark")
print(marks)

marks = marks.drop("Rank5")
print("\nAfter Dropping Rank5")
print(marks)

cgpa = marks / 10
print("\nCGPA")
print(cgpa)



After Changing Rank1 Mark
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After Dropping Rank5
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
# Create dictionary data
data = {
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "ProductCategory": [
        "Electronics",
        "Clothing",
        "Electronics",
        "Furniture",
        "Clothing",
        "Electronics",
        "Furniture",
        "Clothing",
        "Furniture",
        "Electronics"
    ],

    "Region": [
        "North",
        "South",
        "North",
        "East",
        "West",
        "North",
        "East",
        "West",
        "South",
        "North"
    ],

    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

# Create DataFrame  
transactions = pd.DataFrame(data)
print("Transactions DataFrame")
print(transactions)


Transactions DataFrame
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [31]:
# 2. Data Exploration
# First 5 rows
print("\nHead")
print(transactions.head())
# Last 5 rows
print("\nTail")
print(transactions.tail())
# Shape of DataFrame
print("\nShape")
print(transactions.shape)
# Column names
print("\nColumn Names")
print(transactions.columns)
# Data types
print("\nData Types")
print(transactions.dtypes)
# Show only ProductCategory and Amount
print("\nProductCategory and Amount")
print(transactions[["ProductCategory", "Amount"]])
# Last 3 columns using iloc
print("\nLast 3 Columns")
print(transactions.iloc[:, -3:])

# Filter North region and Amount > 200
print("\nNorth Region and Amount Greater Than 200")
print(transactions[
    (transactions["Region"] == "North") &
    (transactions["Amount"] > 200)
])


# Count ProductCategory values
print("\nProduct Category Count")
print(transactions["ProductCategory"].value_counts())


# Unique Region values
print("\nUnique Regions")
print(transactions["Region"].unique())


# Mean amount by Region
print("\nMean Amount By Region")
print(transactions.groupby("Region")["Amount"].mean())




Head
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape
(10, 4)

Column Names
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

Data Types
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

ProductCategory and Amount
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     

In [32]:
# 3. Manipulating DataFrame
# Change Amount for TransactionID 102
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165

print("\nAfter Changing Amount")
print(transactions)


# Add Discount column
# 10% discount
transactions["Discount"] = transactions["Amount"] * 0.10

print("\nAfter Adding Discount")
print(transactions)


# Remove row with TransactionID 109
transactions = transactions[transactions["TransactionID"] != 109]

print("\nAfter Removing TransactionID 109")
print(transactions)


# Delete Discount column
del transactions["Discount"]

print("\nAfter Deleting Discount Column")
print(transactions)


After Changing Amount
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After Adding Discount
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107    